import os

import requests
from tqdm import tqdm

ROWS_PER_PAGE = 100
BASE_SEARCH_URL = "https://archive.org/advancedsearch.php"
METADATA_URL = "https://archive.org/metadata"
DOWNLOAD_BASE = "https://archive.org/download"
HEADERS = {"User-Agent": "archive-downloader (educational use)"}


def build_search_query(
    text="", subjects=None, genres=None, year_from=None, year_to=None, artist=None
):
    """
    Build a search query string for the Internet Archive audio collection.

    Parameters
    ----------
    text : str, optional
        Free text search query.
    subjects : str or list, optional
        Subject tags to filter by.
    genres : str or list, optional
        Genres to filter by.
    year_from : str, optional
        Start year (inclusive).
    year_to : str, optional
        End year (inclusive).
    artist : str, optional
        Artist/creator name.
    """

    def normalize(v):
        if not v:
            return []
        if isinstance(v, str):
            return [x.strip() for x in v.split(",") if x.strip()]
        return v

    def or_block(field, values):
        if not values:
            return None
        values = [f'"{v}"' if " " in v else v for v in values]
        return f"{field}:({' OR '.join(values)})"

    parts = []

    if text:
        parts.append(text)

    subjects = normalize(subjects)
    genres = normalize(genres)

    parts += [f'subject:"{s}"' for s in subjects]

    for block in [or_block("subject", genres)]:
        if block:
            parts.append(block)

    parts += [
        "mediatype:audio",
        "collection:audio_music",
    ]

    if year_from or year_to:
        yf = year_from or "*"
        yt = year_to or "*"
        parts.append(f"year:[{yf} TO {yt}]")

    if artist:
        parts.append(f'creator:("{artist.lower()}")')

    return " AND ".join(parts)


def search_items(page, query):
    """
    Perform a search request against the Internet Archive API.

    Parameters
    ----------
    page : int
        Page number of results to retrieve.
    query : str
        Query string generated by build_search_query.
    """
    params = {
        "q": query,
        "fl[]": "identifier",
        "rows": ROWS_PER_PAGE,
        "page": page,
        "output": "json",
    }
    r = requests.get(BASE_SEARCH_URL, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()["response"]


def get_mp3_files(identifier):
    """
    Retrieve all MP3 filenames for a given Internet Archive item.
    """
    r = requests.get(f"{METADATA_URL}/{identifier}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    data = r.json()

    mp3s = []
    for f in data.get("files", []):
        name = f.get("name", "")
        if name.lower().endswith(".mp3"):
            mp3s.append(name)
    return mp3s


def download_mp3(identifier, filename, dest_dir):
    """
    Download an MP3 file from the Internet Archive.
    """
    url = f"{DOWNLOAD_BASE}/{identifier}/{filename}"
    local_path = os.path.join(dest_dir, filename)

    if os.path.exists(local_path):
        return local_path

    os.makedirs(dest_dir, exist_ok=True)
    with requests.get(url, stream=True, headers=HEADERS, timeout=60) as r:
        try:
            r.raise_for_status()
        except requests.exceptions.HTTPError as e:
            print(f"Error downloading {filename}: {e}")
            return None
        total = int(r.headers.get("content-length", 0))

        with (
            open(local_path, "wb") as f,
            tqdm(
                total=total,
                unit="B",
                unit_scale=True,
                desc=filename,
                leave=False,
            ) as bar,
        ):
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    bar.update(len(chunk))
    return local_path
